export const dropdowns = {
  sources: [
    "Facebook",
    "Instagram",
    "Website",
    "Referral",
    "Past Client",
    "Church",
    "Neighborhood Group",
    "Raffle",
    "In-Person Conversation",
    "Other",
  ],
  stages: [
    "Not Contacted Yet",
    "Contacted / Replied",
    "Qualified",
    "Asked for Pictures",
    "Offered Times",
    "Booked Consult",
    "Showed to Consult",
    "Closed",
    "Nurture After Consult",
    "No for Now",
    "Repeat Customer",
    "Lost",
    "Dead",
  ],
  owners: ["Janae", "Shawntay", "Unassigned"],
  pains: [
    "Moving Soon",
    "Injury or Physical Limitation",
    "New Baby",
    "Divorce",
    "Memory Care Move",
    "Downsizing",
    "Guests Coming",
    "Event Deadline",
    "Strong Anxiety Around the Home",
    "Too Much Stuff / Anxiety",
    "General Clutter",
    "Not Sure Yet",
    "Next Space / Second Project (Repeat Buyer)",
    "Monthly Maintenance (Repeat Buyer)",
    "Product Install / Labeling (Repeat Buyer)",
    "Recently Moved",
    "Other",
  ],
  spaces: [
    "Pantry",
    "Garage",
    "Kitchen",
    "Laundry",
    "Closet",
    "Closet System",
    "Home Office",
    "Office",
    "Playroom",
    "Dining Room",
    "Nursery Storage",
    "Kid's Room",
    "Full Room",
    "Multi-Space",
    "Whole Home",
    "Move / Unpacking",
    "Monthly Maintenance",
    "Labeling / Product Install",
    "Haul-Away Only",
    "Other",
  ],
  decisionMakers: ["Self", "Both Involved", "Final Decision Maker", "Spouse Needed", "Not Decision Maker", "Unknown"],
  budgets: [
    "Comfortable",
    "Comfortable / Done-For-You",
    "Wants Done-For-You",
    "Unsure",
    "Price-Sensitive",
    "Unknown",
  ],
  lostReasons: [
    "No Response",
    "Out of Service Area",
    "Cleaning Only",
    "Extreme Hoarding",
    "Extreme OCD",
    "Budget",
    "Timing",
    "Needs Spouse",
    "Not a Fit",
    "Do Not Contact",
    "No for Now / Timing",
    "Long-Term Nurture",
    "Future Project",
    "Needs Spouse Approval",
    "Payment Plan Needed",
    "Unexpected Expense",
    "Waiting on Photos",
    "Waiting on Decision",
    "Price Too High",
    "Not Service Area",
    "Chose Competitor",
    "DIY",
    "Other",
  ],
  cities: [
    "Dallas",
    "Highland Park",
    "University Park",
    "Addison",
    "Richardson",
    "Plano",
    "Frisco",
    "Allen",
    "McKinney",
    "Prosper",
    "Carrollton",
    "Farmers Branch",
    "Coppell",
    "Irving",
    "Grapevine",
    "Southlake",
    "Flower Mound",
    "Lewisville",
    "The Colony",
    "Garland",
    "Rowlett",
    "Rockwall",
    "Mesquite",
    "Forney",
    "Other",
  ],
};

export const strongPainTriggers = new Set([
  "Moving Soon",
  "Injury or Physical Limitation",
  "New Baby",
  "Divorce",
  "Memory Care Move",
  "Downsizing",
  "Guests Coming",
  "Event Deadline",
  "Strong Anxiety Around the Home",
  "Too Much Stuff / Anxiety",
  "Next Space / Second Project (Repeat Buyer)",
  "Monthly Maintenance (Repeat Buyer)",
  "Product Install / Labeling (Repeat Buyer)",
  "Recently Moved",
]);

export const bigSpaceTriggers = new Set([
  "Garage",
  "Full Room",
  "Multi-Space",
  "Whole Home",
  "Move / Unpacking",
  "Monthly Maintenance",
  "Closet System",
  "Home Office",
  "Kitchen",
  "Playroom",
  "Dining Room",
  "Nursery Storage",
  "Closet",
  "Kid's Room",
]);

export const authorityTriggers = new Set(["Self", "Both Involved", "Final Decision Maker"]);
export const budgetTriggers = new Set(["Comfortable", "Comfortable / Done-For-You", "Wants Done-For-You"]);
export const inactiveStages = new Set(["Closed", "Dead", "Lost", "No for Now"]);
export const lostStages = new Set(["Dead", "Lost"]);

export const tableFields = [
  "name",
  "phone",
  "email",
  "source",
  "stage",
  "owner",
  "pain",
  "spaceNeeded",
  "deadline",
  "decisionMaker",
  "budget",
  "city",
  "lastTouch",
  "nextFollowUpDate",
  "lostReason",
  "notes",
];
